import { StatusDatum } from "./charts/StatusComparisonCard"

export type ProviderRow = {
  id: string
  providerName: string
  providerCode: string
  totalRequests: number
  approved: number
  denied: number
  approvalRate: number
  estimatedCost: number
  service?: string
  location?: string
}

export const MOCK_PROVIDER_ROWS: ProviderRow[] = [
  {
    id: "1",
    providerName: "Hospital XYZ",
    providerCode: "13/O/W7E270",
    totalRequests: 240,
    approved: 90,
    denied: 15,
    approvalRate: 80,
    estimatedCost: 50000,
    service: "inpatient",
    location: "lagos",
  },
  {
    id: "2",
    providerName: "Elvachi Hospital",
    providerCode: "13/O/W7E271",
    totalRequests: 212,
    approved: 70,
    denied: 5,
    approvalRate: 39,
    estimatedCost: 50000,
    service: "outpatient",
    location: "abuja",
  },
  {
    id: "3",
    providerName: "CedarCare Clinic",
    providerCode: "13/O/W7E272",
    totalRequests: 180,
    approved: 62,
    denied: 11,
    approvalRate: 51,
    estimatedCost: 84500,
    service: "labs",
    location: "kano",
  },
  {
    id: "4",
    providerName: "Greenfield Medical",
    providerCode: "13/O/W7E273",
    totalRequests: 320,
    approved: 140,
    denied: 22,
    approvalRate: 73,
    estimatedCost: 132000,
    service: "inpatient",
    location: "rivers",
  },
  {
    id: "5",
    providerName: "PrimeHealth Hospital",
    providerCode: "13/O/W7E274",
    totalRequests: 96,
    approved: 40,
    denied: 6,
    approvalRate: 62,
    estimatedCost: 41000,
    service: "pharmacy",
    location: "lagos",
  },
  {
    id: "6",
    providerName: "St. Mary’s Hospital",
    providerCode: "13/O/W7E275",
    totalRequests: 410,
    approved: 210,
    denied: 30,
    approvalRate: 78,
    estimatedCost: 210000,
    service: "inpatient",
    location: "abuja",
  },
  {
    id: "7",
    providerName: "Metro Diagnostics",
    providerCode: "13/O/W7E276",
    totalRequests: 150,
    approved: 55,
    denied: 8,
    approvalRate: 44,
    estimatedCost: 59000,
    service: "labs",
    location: "lagos",
  },
  {
    id: "8",
    providerName: "Crown Specialist Centre",
    providerCode: "13/O/W7E277",
    totalRequests: 275,
    approved: 120,
    denied: 18,
    approvalRate: 69,
    estimatedCost: 145000,
    service: "outpatient",
    location: "kano",
  },
  {
    id: "9",
    providerName: "Unity Hospital",
    providerCode: "13/O/W7E278",
    totalRequests: 134,
    approved: 48,
    denied: 9,
    approvalRate: 53,
    estimatedCost: 72000,
    service: "inpatient",
    location: "rivers",
  },
  {
    id: "10",
    providerName: "BlueCross Clinic",
    providerCode: "13/O/W7E279",
    totalRequests: 88,
    approved: 32,
    denied: 4,
    approvalRate: 58,
    estimatedCost: 38000,
    service: "outpatient",
    location: "abuja",
  },
  {
    id: "11",
    providerName: "LifeSpring Hospital",
    providerCode: "13/O/W7E280",
    totalRequests: 365,
    approved: 190,
    denied: 27,
    approvalRate: 82,
    estimatedCost: 198000,
    service: "inpatient",
    location: "lagos",
  },
  {
    id: "12",
    providerName: "WellnessPlus Pharmacy",
    providerCode: "13/O/W7E281",
    totalRequests: 205,
    approved: 88,
    denied: 12,
    approvalRate: 61,
    estimatedCost: 91000,
    service: "pharmacy",
    location: "kano",
  },
  {
    id: "13",
    providerName: "NovaCare Hospital",
    providerCode: "13/O/W7E282",
    totalRequests: 148,
    approved: 60,
    denied: 10,
    approvalRate: 57,
    estimatedCost: 68000,
    service: "outpatient",
    location: "rivers",
  },
  {
    id: "14",
    providerName: "Apex Medical Centre",
    providerCode: "13/O/W7E283",
    totalRequests: 250,
    approved: 95,
    denied: 20,
    approvalRate: 66,
    estimatedCost: 120000,
    service: "inpatient",
    location: "abuja",
  },
  {
    id: "15",
    providerName: "RiverView Clinic",
    providerCode: "13/O/W7E284",
    totalRequests: 110,
    approved: 45,
    denied: 7,
    approvalRate: 59,
    estimatedCost: 56000,
    service: "outpatient",
    location: "rivers",
  },
  {
    id: "16",
    providerName: "EverCare Diagnostics",
    providerCode: "13/O/W7E285",
    totalRequests: 190,
    approved: 72,
    denied: 14,
    approvalRate: 49,
    estimatedCost: 77000,
    service: "labs",
    location: "abuja",
  },
  {
    id: "17",
    providerName: "GoldenGate Hospital",
    providerCode: "13/O/W7E286",
    totalRequests: 420,
    approved: 230,
    denied: 35,
    approvalRate: 76,
    estimatedCost: 260000,
    service: "inpatient",
    location: "lagos",
  },
  {
    id: "18",
    providerName: "Harmony Health Centre",
    providerCode: "13/O/W7E287",
    totalRequests: 160,
    approved: 64,
    denied: 9,
    approvalRate: 55,
    estimatedCost: 69000,
    service: "outpatient",
    location: "kano",
  },
  {
    id: "19",
    providerName: "Sunrise Hospital",
    providerCode: "13/O/W7E288",
    totalRequests: 300,
    approved: 150,
    denied: 21,
    approvalRate: 71,
    estimatedCost: 175000,
    service: "inpatient",
    location: "abuja",
  },
  {
    id: "20",
    providerName: "MedPoint Clinic",
    providerCode: "13/O/W7E289",
    totalRequests: 125,
    approved: 50,
    denied: 6,
    approvalRate: 63,
    estimatedCost: 61000,
    service: "pharmacy",
    location: "lagos",
  },
]
export type ProviderSeriesPoint = {
  m: string
  requests: number
  cost: number
}

export const MOCK_PROVIDER_SERIES: ProviderSeriesPoint[] = [
  { m: "Jul", requests: 12000, cost: 15000 },
  { m: "Aug", requests: 24000, cost: 23000 },
  { m: "Sep", requests: 30000, cost: 28000 },
  { m: "Oct", requests: 20000, cost: 18000 },
  { m: "Nov", requests: 15000, cost: 14000 },
  { m: "Dec", requests: 12000, cost: 13000 },
]
export const MOCK_PROVIDER_STATUS: StatusDatum[] = [
  {
    key: "pending",
    label: "Pending",
    value: 25,
    amount: "₦2,040,000",
    percentChip: "20%",
    color: "#1671D9",
  },
  {
    key: "approved",
    label: "Approved",
    value: 30,
    amount: "₦3,300,000",
    percentChip: "45%",
    color: "#1671D9CC",
  },
  {
    key: "denied",
    label: "Denied",
    value: 35,
    amount: "₦1,120,000",
    percentChip: "15%",
    color: "#1671D899",
  },
  {
    key: "queried",
    label: "Queried",
    value: 65,
    amount: "₦1,120,000",
    percentChip: "20%",
    color: "#1671D94D",
  },
]
