import type { EnrolleeRow, MonthSeries } from "./types"

export const MOCK_ROWS: EnrolleeRow[] = [
  {
    id: "1",
    enrolleeName: "Muhammad Sahab",
    enrolleeId: "13/O/W7E27O",
    plan: "Platinum",
    scheme: "NHIS",
    provider: "Cedar Crest Hospital",
    requestDate: "10/09/25",
    requestTime: "7:32 am",
    status: "Approved",
    amount: "₦ 4,384,277",
  },
  {
    id: "2",
    enrolleeName: "Chidinma Isaac",
    enrolleeId: "13/O/W7E27O",
    plan: "Platinum",
    scheme: "NHIS",
    provider: "Cedar Crest Hospital",
    requestDate: "10/09/25",
    requestTime: "7:32 am",
    status: "Rejected",
    amount: "₦ 3,283,484",
  },
  {
    id: "3",
    enrolleeName: "Muhammad Sahab",
    enrolleeId: "13/O/W7E27O",
    plan: "Platinum",
    scheme: "NHIS",
    provider: "Cedar Crest Hospital",
    requestDate: "10/09/25",
    requestTime: "7:32 am",
    status: "Pending",
    amount: "₦ 4,384,277",
  },
  {
    id: "4",
    enrolleeName: "Chidinma Isaac",
    enrolleeId: "13/O/W7E27O",
    plan: "Platinum",
    scheme: "NHIS",
    provider: "Cedar Crest Hospital",
    requestDate: "10/09/25",
    requestTime: "7:32 am",
    status: "Approved",
    amount: "₦ 3,283,484",
  },
  {
    id: "5",
    enrolleeName: "Muhammad Sahab",
    enrolleeId: "13/O/W7E27O",
    plan: "Platinum",
    scheme: "NHIS",
    provider: "Cedar Crest Hospital",
    requestDate: "10/09/25",
    requestTime: "7:32 am",
    status: "Pending",
    amount: "₦ 4,384,277",
  },
  {
    id: "6",
    enrolleeName: "Chidinma Isaac",
    enrolleeId: "13/O/W7E27O",
    plan: "Platinum",
    scheme: "NHIS",
    provider: "Cedar Crest Hospital",
    requestDate: "10/09/25",
    requestTime: "7:32 am",
    status: "Approved",
    amount: "₦ 3,283,484",
  },
]

export const MOCK_SERIES: MonthSeries[] = [
  { m: "Jul", approved: 1200, rejected: 300, pending: 520 },
  { m: "Aug", approved: 1600, rejected: 420, pending: 610 },
  { m: "Sep", approved: 1400, rejected: 380, pending: 580 },
  { m: "Oct", approved: 2600, rejected: 520, pending: 800 },
  { m: "Nov", approved: 1100, rejected: 260, pending: 430 },
  { m: "Dec", approved: 1800, rejected: 410, pending: 720 },
  { m: "Jan", approved: 2200, rejected: 510, pending: 860 },
  { m: "Feb", approved: 1500, rejected: 390, pending: 600 },
  { m: "Mar", approved: 1700, rejected: 460, pending: 690 },
  { m: "Apr", approved: 5600, rejected: 720, pending: 1200 },
  { m: "May", approved: 1900, rejected: 520, pending: 760 },
  { m: "Jun", approved: 3200, rejected: 610, pending: 980 },
]
