export const MOCK_DIAGNOSIS_ROWS = [
  {
    id: "1",
    diagnosis: "Malaria",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 500,
    enrolleeCount: 300,
    cost: 4384277,
    service: "outpatient",
    location: "abuja",
    scheme: "PHIS",
    plan: "platinum",
  },
  {
    id: "2",
    diagnosis: "Typhoid",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 369,
    enrolleeCount: 250,
    cost: 3283484,
    service: "outpatient",
    location: "abuja",
    scheme: "NHIS",
    plan: "platinum",
  },
  {
    id: "3",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 732,
    enrolleeCount: 502,
    cost: 4384277,
    service: "inpatient",
    location: "lagos",
    scheme: "PHIS",
    plan: "gold",
  },
  {
    id: "4",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 292,
    enrolleeCount: 1664,
    cost: 3283484,
    service: "labs",
    location: "lagos",
    scheme: "NHIS",
    plan: "silver",
  },
  {
    id: "5",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 64,
    enrolleeCount: 47,
    cost: 4384277,
    service: "pharmacy",
    location: "abuja",
    scheme: "PHIS",
    plan: "gold",
  },
  {
    id: "6",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 729,
    enrolleeCount: 397,
    cost: 3283484,
    service: "outpatient",
    location: "kano",
    scheme: "NHIS",
    plan: "platinum",
  },
  {
    id: "7",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 64,
    enrolleeCount: 47,
    cost: 4384277,
    service: "labs",
    location: "kano",
    scheme: "PHIS",
    plan: "silver",
  },
  {
    id: "8",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 729,
    enrolleeCount: 397,
    cost: 3283484,
    service: "outpatient",
    location: "rivers",
    scheme: "NHIS",
    plan: "gold",
  },
  {
    id: "9",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 64,
    enrolleeCount: 47,
    cost: 4384277,
    service: "inpatient",
    location: "rivers",
    scheme: "PHIS",
    plan: "platinum",
  },
  {
    id: "10",
    diagnosis: "Cold/Flu",
    provider: "Cedar Crest Hospital",
    timesDiagnosed: 729,
    enrolleeCount: 397,
    cost: 3283484,
    service: "pharmacy",
    location: "lagos",
    scheme: "NHIS",
    plan: "silver",
  },

  // extra to make 20
  {
    id: "11",
    diagnosis: "Hypertension",
    provider: "St. Ives Hospital",
    timesDiagnosed: 210,
    enrolleeCount: 180,
    cost: 2480000,
    service: "outpatient",
    location: "abuja",
    scheme: "PHIS",
    plan: "platinum",
  },
  {
    id: "12",
    diagnosis: "Diabetes",
    provider: "St. Ives Hospital",
    timesDiagnosed: 190,
    enrolleeCount: 155,
    cost: 3120000,
    service: "outpatient",
    location: "lagos",
    scheme: "NHIS",
    plan: "gold",
  },
  {
    id: "13",
    diagnosis: "Gastroenteritis",
    provider: "Reddington Hospital",
    timesDiagnosed: 270,
    enrolleeCount: 200,
    cost: 1985000,
    service: "inpatient",
    location: "lagos",
    scheme: "PHIS",
    plan: "silver",
  },
  {
    id: "14",
    diagnosis: "Asthma",
    provider: "Reddington Hospital",
    timesDiagnosed: 145,
    enrolleeCount: 110,
    cost: 1560000,
    service: "outpatient",
    location: "abuja",
    scheme: "NHIS",
    plan: "platinum",
  },
  {
    id: "15",
    diagnosis: "Migraine",
    provider: "Lagoon Hospital",
    timesDiagnosed: 120,
    enrolleeCount: 98,
    cost: 980000,
    service: "outpatient",
    location: "kano",
    scheme: "PHIS",
    plan: "gold",
  },
  {
    id: "16",
    diagnosis: "Back Pain",
    provider: "Lagoon Hospital",
    timesDiagnosed: 160,
    enrolleeCount: 130,
    cost: 1350000,
    service: "pharmacy",
    location: "rivers",
    scheme: "NHIS",
    plan: "silver",
  },
  {
    id: "17",
    diagnosis: "Ulcer",
    provider: "Evercare Hospital",
    timesDiagnosed: 175,
    enrolleeCount: 120,
    cost: 2220000,
    service: "inpatient",
    location: "abuja",
    scheme: "PHIS",
    plan: "platinum",
  },
  {
    id: "18",
    diagnosis: "Fracture",
    provider: "Evercare Hospital",
    timesDiagnosed: 80,
    enrolleeCount: 60,
    cost: 4100000,
    service: "inpatient",
    location: "lagos",
    scheme: "NHIS",
    plan: "platinum",
  },
  {
    id: "19",
    diagnosis: "Skin Infection",
    provider: "Eko Hospital",
    timesDiagnosed: 140,
    enrolleeCount: 105,
    cost: 1180000,
    service: "labs",
    location: "kano",
    scheme: "PHIS",
    plan: "silver",
  },
  {
    id: "20",
    diagnosis: "Eye Infection",
    provider: "Eko Hospital",
    timesDiagnosed: 95,
    enrolleeCount: 70,
    cost: 860000,
    service: "outpatient",
    location: "rivers",
    scheme: "NHIS",
    plan: "gold",
  },
]

export const MOCK_DIAGNOSIS_TOP = [
  {
    key: "typhoid",
    label: "Typhoid",
    value: 6394,
    percent: 35,
    color: "#1671D9",
  },
  {
    key: "malaria",
    label: "Malaria",
    value: 1594,
    percent: 18,
    color: "#AAB511",
  },
  {
    key: "otherDx",
    label: "Diagnosis here",
    value: 1294,
    percent: 6,
    color: "#D5314D",
  },
  {
    key: "others",
    label: "Others",
    value: 5384,
    percent: 41,
    color: "#EAEAEA",
  },
]

// grouped bars (4 series)
export const MOCK_DIAGNOSIS_MONTHLY = [
  { m: "Jul", s1: 22000, s2: 18000, s3: 14000, s4: 16000 },
  { m: "Aug", s1: 21000, s2: 17500, s3: 13500, s4: 15000 },
  { m: "Sep", s1: 22500, s2: 18500, s3: 15000, s4: 17000 },
  { m: "Oct", s1: 23000, s2: 19000, s3: 14500, s4: 16500 },
  { m: "Nov", s1: 24000, s2: 20000, s3: 15000, s4: 17500 },
  { m: "Dec", s1: 23500, s2: 19500, s3: 14500, s4: 17000 },
  { m: "Jan", s1: 24500, s2: 20500, s3: 15500, s4: 18000 },
  { m: "Feb", s1: 25000, s2: 21000, s3: 16000, s4: 18500 },
  { m: "Mar", s1: 30000, s2: 24000, s3: 19000, s4: 22000 },
  { m: "Apr", s1: 20000, s2: 17000, s3: 12000, s4: 15000 },
  { m: "May", s1: 33000, s2: 26000, s3: 20000, s4: 24000 },
  { m: "Jun", s1: 26000, s2: 21000, s3: 16000, s4: 19000 },
]
